// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY1j5-hkkPy9HPGr4nm6GSbIFRQvsGmpk',
    appId: '1:237072452513:web:99db28729ab34563ce19e0',
    messagingSenderId: '237072452513',
    projectId: 'local-test-alstreid',
    authDomain: 'local-test-alstreid.firebaseapp.com',
    storageBucket: 'local-test-alstreid.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTazWhEQ7TDlV_du1G0mFu3ZGOcj8T2jQ',
    appId: '1:237072452513:android:7a080a0e3ecb2533ce19e0',
    messagingSenderId: '237072452513',
    projectId: 'local-test-alstreid',
    storageBucket: 'local-test-alstreid.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGQfp40Rz8zvl-w5UeFZDLdLb0WX9TNWk',
    appId: '1:237072452513:ios:68d7c29a33727f78ce19e0',
    messagingSenderId: '237072452513',
    projectId: 'local-test-alstreid',
    storageBucket: 'local-test-alstreid.appspot.com',
    iosBundleId: 'com.example.biometrick',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGQfp40Rz8zvl-w5UeFZDLdLb0WX9TNWk',
    appId: '1:237072452513:ios:68d7c29a33727f78ce19e0',
    messagingSenderId: '237072452513',
    projectId: 'local-test-alstreid',
    storageBucket: 'local-test-alstreid.appspot.com',
    iosBundleId: 'com.example.biometrick',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBY1j5-hkkPy9HPGr4nm6GSbIFRQvsGmpk',
    appId: '1:237072452513:web:f87d7ebc99e757cace19e0',
    messagingSenderId: '237072452513',
    projectId: 'local-test-alstreid',
    authDomain: 'local-test-alstreid.firebaseapp.com',
    storageBucket: 'local-test-alstreid.appspot.com',
  );
}
